<a href="https://colab.research.google.com/github/Hansika2346/STML_2303A52409/blob/main/STML_Assinment4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read the data with pandas and find features and target variables.
Normalize the data with min-max scaling
Split the data into train and test.:

In [5]:
import pandas as pd
dp=pd.read_csv('/content/train.csv')
print(dp)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [9]:
y=dp['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [14]:
x=dp.drop('price_range',axis=1)
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]

In [19]:
d=x-x.min()/(x.max()-x.min())
d

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,841.665331,0.0,2.0,0.0,1.0,0.0,6.967742,0.488889,187.333333,1.857143,2.0,20.0,755.666222,2548.931587,8.642857,7.0,18.888889,0.0,0.0,1.0
1,1020.665331,1.0,0.3,1.0,0.0,1.0,52.967742,0.588889,135.333333,2.857143,6.0,905.0,1987.666222,2630.931587,16.642857,3.0,6.888889,1.0,1.0,0.0
2,562.665331,1.0,0.3,1.0,2.0,1.0,40.967742,0.788889,144.333333,4.857143,6.0,1263.0,1715.666222,2602.931587,10.642857,2.0,8.888889,1.0,1.0,0.0
3,614.665331,1.0,2.3,0.0,0.0,0.0,9.967742,0.688889,130.333333,5.857143,9.0,1216.0,1785.666222,2768.931587,15.642857,8.0,10.888889,1.0,0.0,0.0
4,1820.665331,1.0,1.0,0.0,13.0,1.0,43.967742,0.488889,140.333333,1.857143,14.0,1208.0,1211.666222,1410.931587,7.642857,2.0,14.888889,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,793.665331,1.0,0.3,1.0,0.0,1.0,1.967742,0.688889,105.333333,5.857143,14.0,1222.0,1889.666222,667.931587,12.642857,4.0,18.888889,1.0,1.0,0.0
1996,1964.665331,1.0,2.4,1.0,0.0,0.0,38.967742,0.088889,186.333333,3.857143,3.0,915.0,1964.666222,2031.931587,10.642857,10.0,15.888889,1.0,1.0,1.0
1997,1910.665331,0.0,0.7,1.0,1.0,1.0,35.967742,0.588889,107.333333,7.857143,3.0,868.0,1631.666222,3056.931587,8.642857,1.0,4.888889,1.0,1.0,0.0
1998,1511.665331,0.0,0.7,0.0,4.0,1.0,45.967742,-0.011111,144.333333,4.857143,5.0,336.0,669.666222,868.931587,17.642857,10.0,18.888889,1.0,1.0,1.0
1999,509.665331,1.0,1.8,1.0,5.0,1.0,44.967742,0.788889,167.333333,5.857143,16.0,483.0,753.666222,3918.931587,18.642857,4.0,1.888889,1.0,1.0,1.0

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(d,y,test_size=0.2)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim   fc  four_g  int_memory  \
691     1485.665331   0.0          2.4       0.0  7.0     0.0   51.967742
1777     842.665331   0.0          1.1       1.0  1.0     0.0   15.967742
1446    1141.665331   1.0          1.2       1.0  6.0     0.0    5.967742
473      931.665331   1.0          0.3       0.0  1.0     1.0   59.967742
898     1371.665331   1.0          2.5       0.0  7.0     0.0   33.967742
...             ...   ...          ...       ...  ...     ...         ...
833     1367.665331   1.0          1.4       1.0  4.0     0.0    8.967742
609     1211.665331   0.0          2.4       0.0  1.0     1.0   45.967742
1328     506.665331   1.0          1.7       1.0  0.0     1.0   38.967742
395     1895.665331   0.0          0.3       1.0  8.0     1.0    6.967742
1106    1265.665331   0.0          2.4       0.0  1.0     0.0   17.967742

         m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
691  -0.011111   84.333333  3.857143  15.0     1430.0  1746.666222
1777  0.788889  118.333333  6.857143   4.0      593.0   731.666222
1446  0.588889  189.333333  7.857143   8.0      534.0   854.666222
473   0.588889  103.333333  3.857143   2.0      268.0  1077.666222
898   0.288889  192.333333  3.857143  17.0      687.0   936.666222
...        ...         ...       ...   ...        ...          ...
833  -0.011111  114.333333  6.857143   7.0      843.0  1144.666222
609   0.188889  101.333333  3.857143   8.0      611.0  1714.666222
1328  0.588889  141.333333  0.857143   0.0       17.0  1083.666222
395   0.288889  140.333333  1.857143  13.0      447.0   793.666222
1106  0.288889   85.333333  6.857143   2.0     1187.0  1594.666222

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
691    296.931587  12.642857   1.0  14.888889      0.0           1.0   0.0
1777  1733.931587  16.642857   8.0  13.888889      0.0           0.0   1.0
1446   662.931587  11.642857   4.0   4.888889      0.0           1.0   1.0
473   1458.931587   5.642857   1.0  18.888889      1.0           1.0   0.0
898    724.931587  10.642857   3.0  19.888889      1.0           0.0   0.0
...           ...        ...   ...        ...      ...           ...   ...
833   2940.931587  12.642857  12.0  16.888889      0.0           1.0   0.0
609   2248.931587  13.642857   3.0   3.888889      1.0           1.0   1.0
1328  2123.931587   5.642857   0.0  11.888889      1.0           1.0   0.0
395   3683.931587   8.642857   7.0  17.888889      1.0           0.0   0.0
1106   397.931587  15.642857   8.0   2.888889      1.0           1.0   1.0

[1600 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
600     1169.665331   0.0          2.7       1.0   2.0     0.0   39.967742
887     1058.665331   0.0          0.3       1.0   0.0     0.0   49.967742
868      980.665331   1.0          1.7       1.0   0.0     0.0    1.967742
1258    1871.665331   1.0          0.3       1.0  14.0     0.0   48.967742
664      913.665331   1.0          0.3       0.0   0.0     1.0   25.967742
...             ...   ...          ...       ...   ...     ...         ...
1121    1544.665331   0.0          1.1       1.0  15.0     1.0   34.967742
958     1007.665331   0.0          2.3       0.0   3.0     0.0   35.967742
1340    1468.665331   0.0          0.3       0.0   3.0     1.0   57.967742
1807     712.665331   0.0          1.2       1.0   4.0     0.0   52.967742
1401     949.665331   0.0          0.3       0.0   6.0     1.0   54.967742

         m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
600   0.288889  168.333333  5.857143   5.0      427.0   683.666222
887   0.588889  181.333333  7.857143   1.0      519.0  1544.666222
868  -0.011111  135.333333  2.857143   7.0       75.0   687.666222
1258  0.088889  138.333333  6.857143  18.0       81.0  1388.666222
664   0.588889  146.333333  3.857143   0.0      706.0   720.666222
...        ...         ...       ...   ...        ...          ...
1121 -0.011111  172.333333  4.857143  20.0      115.0  1351.666222
958   0.888889  108.333333  0.857143  14.0      825.0  1971.666222
1340  0.388889  149.333333  6.857143   8.0     1699.0  1849.666222
1807  0.688889   97.333333  0.857143  17.0      123.0  1476.666222
1401 -0.011111  123.333333  7.857143   7.0       86.0  1680.666222

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
600   2365.931587  15.642857   8.0   1.888889      1.0           1.0   1.0
887    618.931587   4.642857   3.0  17.888889      0.0           1.0   1.0
868   1538.931587  18.642857  12.0  18.888889      0.0           0.0   0.0
1258  3152.931587  15.642857  15.0   4.888889      1.0           1.0   0.0
664   1121.931587  11.642857   9.0   1.888889      1.0           1.0   1.0
...           ...        ...   ...        ...      ...           ...   ...
1121  3196.931587  13.642857   9.0   5.888889      1.0           0.0   1.0
958   1082.931587   5.642857   4.0   5.888889      0.0           0.0   0.0
1340  1570.931587  16.642857  16.0   1.888889      1.0           0.0   0.0
1807  1461.931587  18.642857  18.0  12.888889      1.0           0.0   1.0
1401  1304.931587   5.642857   5.0   3.888889      1.0           0.0   1.0

[400 rows x 20 columns]
691     0
1777    1
1446    0
473     0
898     0
       ..
833     3
609     2
1328    1
395     3
1106    0
Name: price_range, Length: 1600, dtype: int64
600     1
887     0
868     0
1258    3
664     0
       ..
1121    3
958     1
1340    2
1807    0
1401    0
Name: price_range, Length: 400, dtype: int64

Question 2

1.Read the data with pandas and describe the data
2.Find data type and shape of each column
3.Find the target and features
4.Find the null values (if yes fill the null values with ‘0’ or mean of that column)
5.Normalize all the features
6.Split the data into train and test.

In [25]:
import pandas as pd
d=pd.read_csv('/content/sample_data/california_housing_train.csv')
d

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [26]:
d.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [27]:
d.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [28]:
d.shape[0]

17000

In [29]:
x=d.drop('median_house_value',axis=1)
y=d['median_house_value']
print(x)
print(y)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
2           333.0       117.0         1.6509
3           515.0       226.0         3.1917
4           624.0       262.0         1.9250
...           ...         ...            ...
16995       907.0       369.0         2.3571
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797
16999       806.0       270.0         3.0147

[17000 rows x 8 columns]
0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [30]:
d.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [31]:
upd=x-x.min()/x.max()-x.min()
upd

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,8.952169,0.874315,13.980769,5609.999947,1281.999845,1011.999916,470.999836,0.960374
1,8.792169,1.084315,17.980769,7647.999947,1899.999845,1125.999916,461.999836,1.286774
2,8.702169,0.374315,15.980769,717.999947,172.999845,329.999916,115.999836,1.117674
3,8.692169,0.324315,12.980769,1498.999947,335.999845,511.999916,224.999836,2.658474
4,8.692169,0.254315,18.980769,1451.999947,324.999845,620.999916,260.999836,1.391774
...,...,...,...,...,...,...,...,...
16995,-0.997831,7.264315,50.980769,2214.999947,392.999845,903.999916,367.999836,1.823874
16996,-1.007831,7.374315,34.980769,2346.999947,526.999845,1190.999916,463.999836,1.984674
16997,-1.037831,8.524315,15.980769,2674.999947,529.999845,1240.999916,454.999836,2.498074
16998,-1.037831,8.484315,17.980769,2669.999947,550.999845,1294.999916,476.999836,1.446474
16999,-1.087831,7.224315,50.980769,1817.999947,298.999845,802.999916,268.999836,2.481474

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(upd,y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7303    4.922169  0.674315           46.980769  2006.999947      333.999845
12831   1.452169  3.914315           17.980769  2632.999947      425.999845
13976   1.222169  4.354315           27.980769  1691.999947      249.999845
3268    5.402169  0.414315           28.980769  2648.999947      570.999845
7206    4.932169  0.684315           45.980769   822.999947      185.999845
...          ...       ...                 ...          ...             ...
500     6.272169 -0.485685           18.980769  6693.999947     1324.999845
12077   1.832169  5.864315           34.980769  1121.999947      182.999845
15277   0.982169  4.564315           50.980769  1169.999947      213.999845
4517    5.222169  0.444315           14.980769  2067.999947      261.999845
5925    5.052169  0.784315           45.980769  5074.999947     1269.999845

        population   households  median_income
7303    915.999916   295.999836       4.279274
12831  1493.999916   408.999836       5.784574
13976   686.999916   240.999836       5.516874
3268   3245.999916   550.999836       3.186974
7206    412.999916   171.999836       1.800074
...            ...          ...            ...
500    3683.999916  1289.999836       2.664674
12077   500.999916   169.999836       1.633474
15277   485.999916   216.999836       3.383474
4517    874.999916   295.999836       6.554674
5925   3344.999916  1104.999836       2.504474

[13600 rows x 8 columns]
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10914   2.412169  4.194315            3.980769  2896.999947      743.999845
6241    5.012169  0.914315           35.980769  1951.999947      366.999845
5904    5.062169  0.474315           45.980769  2546.999947      624.999845
9578    3.912169  3.204315           37.980769  3024.999947      606.999845
9444    4.012169  0.984315           32.980769  1186.999947      218.999845
...          ...       ...                 ...          ...             ...
12228   1.792169  5.234315           50.980769  1381.999947      293.999845
6639    4.982169  0.594315           39.980769   617.999947      131.999845
7850    4.862169  1.384315            8.980769  4119.999947      812.999845
4886    5.162169  0.694315           40.980769  1433.999947      296.999845
3618    5.352169  0.294315           25.980769  1794.999947      341.999845

        population  households  median_income
10914  1589.999916  631.999836       1.695974
6241    963.999916  368.999836       4.552974
5904   1384.999916  604.999836       2.480274
9578   2195.999916  590.999836       2.111274
9444    441.999916  201.999836       4.349174
...            ...         ...            ...
12228   557.999916  242.999836       1.490974
6639    638.999916  160.999836       2.121374
7850   2160.999916  708.999836       3.760874
4886   1001.999916  296.999836       2.896474
3618    431.999916  201.999836       5.386374

[3400 rows x 8 columns]
7303     170500.0
12831    248000.0
13976    254200.0
3268     182100.0
7206     133300.0
           ...
500      154600.0
12077     93800.0
15277    235600.0
4517     338800.0
5925     186800.0
Name: median_house_value, Length: 13600, dtype: float64
10914    127500.0
6241     261300.0
5904     192700.0
9578      62000.0
9444     396400.0
           ...
12228     94600.0
6639     159600.0
7850     151600.0
4886     195800.0
3618     500001.0
Name: median_house_value, Length: 3400, dtype: float64